### ISSUE TITLE
ImportError: No module named sstruct

### ISSUE THREAD

**Issue by YuyQuan** [typesupply/woffTools#7]
```
quans-Mac:woffTools quan$ ls
Lib     build       setup.py    woff-info
License.txt dist        woff-all    woff-proof
README.txt  font1       woff-css    woff-validate
quans-Mac:woffTools quan$ woff-css font1
Traceback (most recent call last):
  File "/usr/local/bin/woff-css", line 4, in <module>
    __import__('pkg_resources').run_script('woffTools==0.1b0', 'woff-css')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/woffTools-0.1b0-py2.7.egg/EGG-INFO/scripts/woff-css", line 3, in <module>
    __requires__ = 'woffTools==0.1b0'
  File "build/bdist.macosx-10.11-x86_64/egg/woffTools/__init__.py", line 13, in <module>
ImportError: No module named sstruct
quans-Mac:woffTools quan$ 
```

**Comment by typemytype** [comment]
https://github.com/behdad/fonttools is required

`sstruct` is part of fontTools

**Comment by typemytype** [comment]
But `sstruct` is moved to `fontTools.misc.sstruct`

**Comment by typemytype** [comment]
https://github.com/typesupply/woffTools/blob/master/Lib/woffTools/__init__.py#L13

--> `from fontTools.misc import struct`

@typesupply I can fork-clone-edit-push-pull tomorrow if you wish

**Comment by YuyQuan** [comment]
SURE IF YOU THINK'LL MAKE THE CODE WORK

**Comment by anthrotype** [comment]
There's no need to shout ;)
